export const projects = [
  {
    name: "Personal Blog",
    createdOn: "January 21, 2022",
    id: 1,
    issues: [
      {
        name: "Validation error while login",
        id: 1,
        submitter: "Michael Scott",
        submittedOn: "January 22, 2022",
        type: "Development",
        status: "no status",
        comments: [],
      },
      {
        name: "Heading Typo",
        id: 2,
        submitter: "Henry parker",
        submittedOn: "January 22, 2022",
        type: "UIDesign",
        status: "no status",
        comments: [],
      },
      {
        name: "Object not responding",
        id: 3,
        submitter: "Dwight Schrute",
        submittedOn: "January 22, 2022",
        type: "Development",
        status: "completed",
        comments: [],
      },
      {
        name: "New icons for landing page",
        id: 4,
        submitter: "Jim Halpert",
        submittedOn: "January 22, 2022",
        type: "UIDesign",
        status: "in progress",
        comments: [],
      },
      {
        name: "Infinite loading screen",
        id: 5,
        submitter: "Sean Parker",
        submittedOn: "January 22, 2022",
        type: "Development",
        status: "no status",
        comments: [],
      },
    ],
  },
  {
    name: "Futsal Booking App",
    createdOn: "March 11, 2022",
    id: 2,
  },
  {
    name: "Library Management",
    createdOn: "March 20, 2022",
    id: 3,
  },
];
